language: ruby

rvm:
 - 1.9.3
 - 2.0.0
 - 2.1.1
 - 2.2.1
 - rbx-2

gemfile:
  - gemfiles/Gemfile-rails-4-0
  - gemfiles/Gemfile-rails-4-1
  - gemfiles/Gemfile-rails-4-2
  - gemfiles/Gemfile-sprockets-2-11
  - gemfiles/Gemfile-sprockets-2-12
  - gemfiles/Gemfile-sprockets-2-8
  - gemfiles/Gemfile-sprockets-3-0
  - gemfiles/Gemfile-sass-3-1
  - gemfiles/Gemfile-sass-3-2
  - gemfiles/Gemfile-sass-3-3
  - gemfiles/Gemfile-sass-3-4

sudo: false

script: bundle exec rake test

matrix:
  allow_failures:
    - rvm: rbx-2
  include:
    - gemfile: Gemfile
      rvm: 2.2.1

notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#rails-contrib"
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "CGWvthGkBKNnTnk9YSmf9AXKoiRI33fCl5D3jU4nx3cOPu6kv2R9nMjt9EAo\nOuS4Q85qNSf4VNQ2cUPNiNYSWQ+XiTfivKvDUw/QW9r1FejYyeWarMsSBWA+\n0fADjF1M2dkDIVLgYPfwoXEv7l+j654F1KLKB69F0F/netwP9CQ="
